name       : budgie-desktop-view
version    : '1.2'
release    : 22
source     :
    - https://github.com/BuddiesOfBudgie/budgie-desktop-view/archive/refs/tags/v1.2.tar.gz : cbb2567fdf4835f75f4909c81a14e88f57422abe36225ab17a238ca415b54f64
license    : Apache-2.0
component  : desktop.budgie
summary    : Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
description: |
    Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure -Dwith-stateless=true
build      : |
    %ninja_build
install    : |
    %ninja_install
