name       : budgie-desktop-view
version    : 0.99.1
release    : 5
source     :
    - git|https://dev.getsol.us/source/budgie-desktop-view-src.git : 4426924ee57c938f793b6ac3f744ca411368244f
license    : Apache-2.0
component  : desktop.budgie
summary    : Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
description: |
    Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure -Dwith-stateless=true
build      : |
    %ninja_build
install    : |
    %ninja_install
