name       : budgie-desktop-view
version    : 0.99.3
release    : 9
source     :
    - https://getsol.us/sources/budgie-testing/budgie-desktop-view-v0.99.3.tar.xz : 8b95672c24c4fc902e4ed5995e53045133b7e8dc617bc15d0113eedcd6882e49
license    : Apache-2.0
component  : desktop.budgie
summary    : Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
description: |
    Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure -Dwith-stateless=true
build      : |
    %ninja_build
install    : |
    %ninja_install
