name       : budgie-desktop-view
version    : 1.0.2
release    : 17
source     :
    - git|https://github.com/getsolus/budgie-desktop-view.git : 2c933a76e2f5810b9a28889f58a30f138d3a435d
license    : Apache-2.0
component  : desktop.budgie
summary    : Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
description: |
    Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure -Dwith-stateless=true
build      : |
    %ninja_build
install    : |
    %ninja_install
