name       : budgie-desktop-view
version    : 0.99.1
release    : 7
source     :
    - git|https://dev.getsol.us/source/budgie-desktop-view-src.git : a08aff0f2a0201297003c93c345e46efe90bd6b0
license    : Apache-2.0
component  : desktop.budgie
summary    : Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
description: |
    Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure -Dwith-stateless=true
build      : |
    %ninja_build
install    : |
    %ninja_install
