name       : budgie-desktop-view
version    : 0.99.3
release    : 10
source     :
    - https://github.com/getsolus/budgie-desktop-view/releases/download/0.99.3/budgie-desktop-view-v0.99.3.tar.xz : 1d27ed9df2310cb4672ee86a563b237a8777027deef702cc3a0d726ffc4943b3
license    : Apache-2.0
component  : desktop.budgie
summary    : Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
description: |
    Budgie Desktop View is the official Budgie desktop icons implementation, developed by Solus.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure -Dwith-stateless=true
build      : |
    %ninja_build
install    : |
    %ninja_install
